FROM inseefrlab/onyxia-jupyter-python:py3.13.13

USER root
WORKDIR /opt/qgis-agent

COPY agent/ .
RUN pip install -e . --quiet --no-cache-dir

ENV SERVICE_NAME=qgis-agent \
    SERVER_MODULE=agent.main:app \
    SERVER_PORT=8888

USER 1000
